name:                hpke
version:             0.1.0.0
github:              "ocheron/hs-hpke"
license:             BSD3
author:              "Olivier Chéron"
maintainer:          "olivier.cheron@gmail.com"
copyright:           "2020 Olivier Chéron"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Hybrid Public Key Encryption
category:            Crypto

description: |
    Hybrid Public Key Encryption (HPKE) implemented in Haskell.

    HPKE schemes combine asymmetric and symmetric algorithms in an interoperable
    standard.

dependencies:
- base >= 4.7 && < 5
- bytestring
- cryptonite >= 0.25

ghc-options:
- -Wall

library:
  source-dirs: src
  exposed-modules:
  - Crypto.PubKey.HPKE
  dependencies:
  - memory >= 0.14.18

tests:
  hpke-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpke
    - tasty
    - tasty-quickcheck
